name: Deploy to Cloud Run and Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    # Only run deployment job for push to main or PR from same repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          retries: 3
          backoff: 250
          id_token_include_email: false

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Check Cloud Run API enabled
        run: |
          if ! gcloud services list --enabled --project=${{ secrets.GCP_PROJECT_ID }} | grep -q run.googleapis.com; then
            echo "::error::Cloud Run API (run.googleapis.com) is not enabled for this project. Please enable it in the Google Cloud Console."
            exit 1
          fi

      - name: Build & Deploy to Cloud Run
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=global \
            --timeout=1200s \
            --machine-type=e2-medium 
            
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      # Removed Node.js setup and npm install steps

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
            repoToken: ${{ secrets.GITHUB_TOKEN }}
            firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
            channelId: live
            projectId: trag-image-alchemist
            expires: 7d
            entryPoint: .
            firebaseToolsVersion: latest
      - name: Verify firebase.json exists
        run: |
         test -f ./firebase.json || (echo "::error::firebase.json not found in ./web"; exit 1)
    