name: Deploy to Firebase
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g firebase-tools
          echo "Dependencies installed successfully!"

      - name: Build Project
        run: |
          echo "Building project..."
          python build.py || exit 1
          echo "Build completed!"
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Run Tests
        run: |
          echo "Running tests..."
          python -m pytest || exit 1
          echo "Tests completed successfully!"
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          
      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Starting deployment to Firebase..."
          firebase deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive || {
            echo "Deployment failed"
            exit 1
          }
          echo "Deployment successful!"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
